format_version: 10
pipelines:
  frontend:
    group: defaultGroup
    materials:
      git-683112d:
        git: https://github.com/a78devops/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - dev:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible-playbook:
            tasks:
            - exec:
                arguments:
                  - ansible.sh
                  - frontend
                command: bash #bash ansible.sh frontend
                run_if: passed
    - QA:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible-playbook:
            tasks:
            - exec:
                arguments:
                   - ansible.sh
                   - frontend
                command: bash #bash ansible.sh frontend
                run_if: passed

    - STAGE:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          ansible-playbook:
            tasks:
            - exec:
                arguments:
                  - ansible.sh
                  - frontend
                command: bash #bash ansible.sh frontend
                run_if: passed
    - PROD:
        fetch_materials: true
        approval:
           type: manual
        jobs:
           ansible-playbook:
             tasks:
             - exec:
                  arguments:
                    - ansible.sh
                    - frontend
                  command: bash #bash ansible.sh frontend
                  run_if: passed