- name: set prompt with component
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

- name: install node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter

- name: install logstash
  ansible.builtin.import_role:
    name: logstash

